version: '3.8'

services:
  postgres:
    container_name: samurai_db
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: samurai
      POSTGRES_PASSWORD: password
      POSTGRES_USER: samurai
    ports:
      - '5433:5432'
    networks:
      - samurai_network

networks:
  samurai_network:
    driver: bridge
